# Question One 
- Create a 6x6 NumPy array with random integers between 1 and 50. Display the array

In [2]:
import numpy as np
import matplotlib.pyplot as plt

array = np.random.randint(1, 51, size=(6,6))
print("Array:\n", array)

Array:
 [[36 15 41 28  1  8]
 [17 50 27 17 11 46]
 [45  7 23  6 12 27]
 [40 13 43 16  1  2]
 [33 23  4 27  1 43]
 [ 4 36  3 45 29 48]]


# Question 2
- Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


In [3]:
first_two_rows = array[0:2]
print("First two rows:\n", first_two_rows)

last_three_columns = array[:6, 3:]
print("\nLast three columns:\n", last_three_columns)

even_numbers = array[array%2 == 0]
print('\nEven Numbers:\n', even_numbers)

First two rows:
 [[36 15 41 28  1  8]
 [17 50 27 17 11 46]]

Last three columns:
 [[28  1  8]
 [17 11 46]
 [ 6 12 27]
 [16  1  2]
 [27  1 43]
 [45 29 48]]

Even Numbers:
 [36 28  8 50 46  6 12 40 16  2  4  4 36 48]


# Question 3
- Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [4]:
reshape_array_3D = array.reshape(3,2,6)
print("3D Reshape:\n", reshape_array_3D)

flatten_array_1D = array.flatten()
print("\nFlattened 1D:\n", flatten_array_1D)

3D Reshape:
 [[[36 15 41 28  1  8]
  [17 50 27 17 11 46]]

 [[45  7 23  6 12 27]
  [40 13 43 16  1  2]]

 [[33 23  4 27  1 43]
  [ 4 36  3 45 29 48]]]

Flattened 1D:
 [36 15 41 28  1  8 17 50 27 17 11 46 45  7 23  6 12 27 40 13 43 16  1  2
 33 23  4 27  1 43  4 36  3 45 29 48]


# Question 4
- Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [5]:
identity_matrix = np.eye(4)
print("Identity matrix:\n", identity_matrix)


np.fill_diagonal(array, np.arange(10,50,10))
print("\nDiagonal matrix:\n", array)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal matrix:
 [[10 15 41 28  1  8]
 [17 20 27 17 11 46]
 [45  7 30  6 12 27]
 [40 13 43 40  1  2]
 [33 23  4 27 10 43]
 [ 4 36  3 45 29 20]]


# Question 5
- Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [6]:
matrix_1 = np.random.randint(1, 11, size=(3,4))
print("First Matrix (3x4):\n", matrix_1)

matrix_2 = np.random.randint(1, 11, size=(4,3))
print("\nSecond Matrix (4x3):\n", matrix_2)

matrix_multiplication = np.matmul(matrix_1, matrix_2)
matrix_multiplication1 = np.dot(matrix_1, matrix_2)
print("\nThe matrix multiplication:\n", matrix_multiplication)
print("\nThe matrix multiplication1:\n", matrix_multiplication1)


First Matrix (3x4):
 [[ 2 10  4  7]
 [ 3 10  3  7]
 [ 5 10  8  5]]

Second Matrix (4x3):
 [[9 3 3]
 [8 8 8]
 [1 7 3]
 [3 4 2]]

The matrix multiplication:
 [[123 142 112]
 [131 138 112]
 [148 171 129]]

The matrix multiplication1:
 [[123 142 112]
 [131 138 112]
 [148 171 129]]


# Question 6
- Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [ ]:
def numpy_2D(input_arr):
    array = np.array(input_arr).reshape(2, -1)      #Reshape the inputted array into a 2 by x array

    output = np.where(array%2 ==0, array**2, -1)
    return f"New Array:\n {output}"
    
    # This checks for even numbers and replace it with the square of even numbers and -1 to that of odd.
list_array = []

for i in range(6):
    list_input = int(input("Enter the numbers: %d "))
    list_array.append(list_input)

print("Original matrix:\n", list_array)
print(numpy_2D(list_array))

[3, 9, 4, 2, 8, 6]
New Array:
 [[-1 -1 16]
 [ 4 64 36]]
