# Question One 
- Create a 6x6 NumPy array with random integers between 1 and 50. Display the array

In [36]:
import numpy as np
import matplotlib.pyplot as plt

array = np.random.randint(1, 51, size=(6,6))
print("Array:\n", array)

Array:
 [[22 16 22 15 19 29]
 [ 8  9 37 35 38  8]
 [ 3 29 39 44  8 35]
 [20 13 31 49 43 26]
 [27 43 28 39  4 45]
 [50 47 26 28 13 30]]


# Question 2
- Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


In [37]:
first_two_rows = array[0:2]
print("First two rows:\n", first_two_rows)

last_three_columns = array[:6, 3:]
print("\nLast three columns:\n", last_three_columns)

even_numbers = array[array%2 == 0]
print('\nEven Numbers:\n', even_numbers)

First two rows:
 [[22 16 22 15 19 29]
 [ 8  9 37 35 38  8]]

Last three columns:
 [[15 19 29]
 [35 38  8]
 [44  8 35]
 [49 43 26]
 [39  4 45]
 [28 13 30]]

Even Numbers:
 [22 16 22  8 38  8 44  8 20 26 28  4 50 26 28 30]


# Question 3
- Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [41]:
reshape_array_3D = array.reshape(3,2,6)
print("3D Reshape:\n", reshape_array_3D)

flatten_array_1D = array.flatten()
print("\nFlattened 1D:\n", flatten_array_1D)

3D Reshape:
 [[[22 16 22 15 19 29]
  [ 8  9 37 35 38  8]]

 [[ 3 29 39 44  8 35]
  [20 13 31 49 43 26]]

 [[27 43 28 39  4 45]
  [50 47 26 28 13 30]]]

Flattened 1D:
 [22 16 22 15 19 29  8  9 37 35 38  8  3 29 39 44  8 35 20 13 31 49 43 26
 27 43 28 39  4 45 50 47 26 28 13 30]


# Question 4
- Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [59]:
identity_matrix = np.eye(4)
print("Identity matrix:\n", identity_matrix)


np.fill_diagonal(array, np.arange(10,50,10))
print("\nDiagonal matrix:\n", array)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal matrix:
 [[10 16 22 15 19 29]
 [ 8 20 37 35 38  8]
 [ 3 29 30 44  8 35]
 [20 13 31 40 43 26]
 [27 43 28 39 10 45]
 [50 47 26 28 13 20]]


# Question 5
- Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [62]:
matrix_1 = np.random.randint(1, 11, size=(3,4))
print("First Matrix (3x4):\n", matrix_1)

matrix_2 = np.random.randint(1, 11, size=(4,3))
print("\nSecond Matrix (4x3):\n", matrix_2)

matrix_multiplication = np.matmul(matrix_1, matrix_2)
matrix_multiplication1 = np.dot(matrix_1, matrix_2)
print("\nThe matrix multiplication:\n", matrix_multiplication)
print("\nThe matrix multiplication1:\n", matrix_multiplication1)


First Matrix (3x4):
 [[ 2  2  1  8]
 [ 2  6  5  9]
 [ 8  9  5 10]]

Second Matrix (4x3):
 [[ 6 10  1]
 [10  6  4]
 [ 8  8  9]
 [ 5  2  8]]

The matrix multiplication:
 [[ 80  56  83]
 [157 114 143]
 [228 194 169]]

The matrix multiplication1:
 [[ 80  56  83]
 [157 114 143]
 [228 194 169]]


# Question 6
- Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [ ]:
def numpy_2D(input_arr):
    squared_even = np.square(input_arr[input_arr%2 == 0])
    odd_num = 
    new_arr = input_arr[input_arr%2 == 0]
    np.sq
    return new_arr