# **Class Task 2 Solution**

#### **Question one**

Matrix A contains **2 rows and 3 columns** while Matrix B contains **3 rows and 2 columns**

#### **Question Two**

The matrices can be multiplied. For **(AB)**: the number of columns of matrix A which is **3** is equal to the number of rows of matrix B which is also **3**. Same applies to **(BA)**, which the number of columns of matrix B which is **2** is equal to the number of rows of matrix A which is **2**. Hence, it will be both

#### **Question Three**

In [ ]:
import numpy as np

matrix_A = np.array([[2, -1, 3], [0, 4, 1]])
print(f"\nMatrix A:\n{matrix_A}\n============")

matrix_B = np.array([[1, 2], [-2, 0], [5, -3]])
print(f"Matrix B:\n{matrix_B}")

matrix_AB = matrix_A.dot(matrix_B)
print(f"\n===========================\n")
print(f"The Resulting matrix for A X B is:\n\n{matrix_AB}")


matrix_BA = matrix_B.dot(matrix_A)
print(f"\n============================\n")
print(f"The Resulting matrix for B X A is:\n\n{matrix_BA}")


Matrix A:
[[ 2 -1  3]
 [ 0  4  1]]
Matrix B:
[[ 1  2]
 [-2  0]
 [ 5 -3]]


The Resulting matrix for A X B is:

[[19 -5]
 [-3 -3]]


The Resulting matrix for B X A is:

[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
