## **LINEAR ALGEBRA CLASS TASK**

### **Case Study: Student Performance Analysis with Linear Algebra**

**Add-on Exercises**
1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total
score and the average per subject.
2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar
multiplication and recompute totals.
3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using
matrix multiplication.
4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each
subject?

In [2]:
# Import necessary library
import numpy as np

In [32]:
# Creating a 5x4 matrix (5 students and 4 subjects)
# Meaning 5 rows and 4 columns
# Creating the student's data below
'''
students            Science     English     Maths           CCA
Student 1              75          70        90             65     
Student 2              80          72        80             62     
Student 3              65          55        90             70     
Student 4              75          90        70             95     
Student 5              73          89        69             80     
'''

student_data = np.array([[75, 70, 90, 65],
                        [80, 72, 80, 62],
                        [65, 55, 90, 70],
                        [75, 90, 70, 95],
                        [73, 89, 69, 80]]
                        )

In [33]:
student_data

array([[75, 70, 90, 65],
       [80, 72, 80, 62],
       [65, 55, 90, 70],
       [75, 90, 70, 95],
       [73, 89, 69, 80]])

1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total
score and the average per subject.

In [4]:
# Calculating each Student's total score
student1 = np.sum(student_data[0,:])
print(f"The total score for student 1 is: {student1}")

student2 = np.sum(student_data[1,:])
print(f"The total score for student 2 is: {student2}")

student3 = np.sum(student_data[2,:])
print(f"The total score for student 3 is: {student3}")

student4 = np.sum(student_data[3,:])
print(f"The total score for student 4 is: {student4}")

student5 = np.sum(student_data[4,:])
print(f"The total score for student 5 is: {student5}")




The total score for student 1 is: 300
The total score for student 2 is: 294
The total score for student 3 is: 280
The total score for student 4 is: 330
The total score for student 5 is: 311


In [27]:
# Getting the total score per subject and taking the average
science = np.sum(student_data[:,0])
print(f"\nThe total score for Science: {science}")
average_science = science / student_data.shape[0]
print(f"\tThe average score for Science: {average_science}")

english = np.sum(student_data[:,1])
print(f"\nThe total score for English: {english}")
average_english = english / student_data.shape[0]
print(f"\tThe average score for English: {average_english}")

maths = np.sum(student_data[:,2])
print(f"\nThe total score for Maths: {maths}")
average_maths = maths / student_data.shape[0]
print(f"\tThe average score for Maths: {average_maths}")

cca = np.sum(student_data[:,3])
print(f"\nThe total score for CCA: {cca}")
average_cca = cca / student_data.shape[0]
print(f"\tThe average score for CCA: {average_cca}")



The total score for Science: 368
	The average score for Science: 73.6

The total score for English: 376
	The average score for English: 75.2

The total score for Maths: 399
	The average score for Maths: 79.8

The total score for CCA: 372
	The average score for CCA: 74.4


2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar
multiplication and recompute totals.

In [37]:
# Assuming Science is 3 times greater over other subjects

subject_scalar = [3, 1, 1, 1]

# Scalar multiplication
new_scalar_data = np.array([np.dot(subject_scalar[0], student_data[:, 0]), np.dot(subject_scalar[1], student_data[:, 1]), np.dot(subject_scalar[2], student_data[:, 2]), np.dot(subject_scalar[3], student_data[:, 3])]).transpose()
print(f"The new data after scalar multiplication is:\n{new_scalar_data}")

#  Recomputing totals across each subjects
new_science = np.sum(new_scalar_data[:, 0])
print(f"\nThe new total score for Science: {new_science}")

new_english = np.sum(new_scalar_data[:, 1])
print(f"\nThe new total score for English: {new_english}")

new_maths = np.sum(new_scalar_data[:, 2])
print(f"\nThe new total score for Maths: {new_maths}")

new_cca = np.sum(new_scalar_data[:, 3])
print(f"\nThe new total score for CCA: {new_cca}")


The new data after scalar multiplication is:
[[225  70  90  65]
 [240  72  80  62]
 [195  55  90  70]
 [225  90  70  95]
 [219  89  69  80]]

The new total score for Science: 1104

The new total score for English: 376

The new total score for Maths: 399

The new total score for CCA: 372
