In [2]:
# Import the necessary library
import numpy as np


In [ ]:
# QUESTION A

matrix_A = np.array([[2, -1], [0, 3]])

matrix_B = np.array([[1, 4], [-2, 5]])

# Scalar values
scalar_c = 2

scalar_d = 3

# Computation 
# Broadcasting was done below. It is a mechanism that allows NumPy to perform operations on arrays of different shapes.
computed_cA = scalar_c*(matrix_A)

computed_dB = scalar_d*(matrix_B)

computed_ = (scalar_c + scalar_d)*(matrix_A)

print(f"Matrix A is:\n{matrix_A}")

print(f"\nMatrix B is:\n{matrix_B}")

print(f"\ncA is:\n{computed_cA}")

print(f"\ndB is:\n{computed_dB}")

print(f"\n(c+d)A is:\n{computed_}")


Matrix A is:
[[ 2 -1]
 [ 0  3]]

Matrix B is:
[[ 1  4]
 [-2  5]]

cA is:
[[ 4 -2]
 [ 0  6]]

dB is:
[[ 3 12]
 [-6 15]]

(c+d)A is:
[[10 -5]
 [ 0 15]]


In [17]:
# QUESTION B
# 1. For the Associativity of Scalar Multiplication:
# (c.d)A = c.(dA)
lhs_operation = (scalar_c * scalar_d)*matrix_A
rhs_operation = scalar_c * (scalar_d * matrix_A)
print(f"\nThe associativity of scalar multiplication property is: {np.array_equal(lhs_operation, rhs_operation)}")

# 2. For the Distributivity over Matrix Addition:
# c(A + B) = cA + cB
lhs_operation2 = scalar_c * (matrix_A + matrix_B)
rhs_operation2 = (scalar_c * matrix_A) + (scalar_c * matrix_B)
print(f"\nThe distributivity over Matrix Addition property is: {np.array_equal(lhs_operation2, rhs_operation2)}")

# 3. Distributivity over Scalar Addition: 
# (c + d)A = cA + dA
lhs_operation3 = (scalar_c + scalar_d) * matrix_A
rhs_operation3 = (scalar_c * matrix_A) + (scalar_d * matrix_A)
print(f"\nThe distributivity over Scalar Addition property is: {np.array_equal(lhs_operation3, rhs_operation3)}")


The associativity of scalar multiplication property is: True

The distributivity over Matrix Addition property is: True

The distributivity over Scalar Addition property is: True


In [9]:
# QUESTION C
# Find the Transpose for both matrices

matrix_A_transpose = matrix_A.transpose()
print(f"\nThe transpose of matrix A is:\n{matrix_A_transpose}")


matrix_B_transpose = matrix_B.T     # ".T" ia also another method for finding transpose
print(f"\nThe transpose of matrix B is:\n{matrix_B_transpose}")


The transpose of matrix A is:
[[ 2  0]
 [-1  3]]

The transpose of matrix B is:
[[ 1 -2]
 [ 4  5]]
