In [2]:
# Import the necessary library
import numpy as np


In [6]:
matrix_A = np.array([[2, -1], [0, 3]])

matrix_B = np.array([[1, 4], [-2, 5]])

# Scalar values
scalar_c = 2

scalar_d = 3

# Computation 
# Broadcasting was done below. It is a mechanism that allows NumPy to perform operations on arrays of different shapes.
computed_cA = scalar_c*(matrix_A)

computed_dB = scalar_d*(matrix_B)

computed_ = (scalar_c + scalar_d)*(matrix_A)

print(f"Matrix A is:\n{matrix_A}")

print(f"\nMatrix B is:\n{matrix_B}")

print(f"\ncA is:\n{computed_cA}")

print(f"\ndB is:\n{computed_dB}")

print(f"\n(c+d)A is:\n{computed_}")


Matrix A is:
[[ 2 -1]
 [ 0  3]]

Matrix B is:
[[ 1  4]
 [-2  5]]

cA is:
[[ 4 -2]
 [ 0  6]]

dB is:
[[ 3 12]
 [-6 15]]

(c+d)A is:
[[10 -5]
 [ 0 15]]
